
package com.mycompany.autostockcar.view.componentes;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;

public class Mensagem extends javax.swing.JPanel {
private TipoMensagem tipoMensagem;
    private boolean mostra;

    public Mensagem() {
        initComponents();
        setVisible(false);
        setOpaque(false);
    }

    public enum TipoMensagem {
        SUCESSO, ERRO
    }
    
    public void mostrarMensagem(TipoMensagem tipo, String mensagem) {
        this.tipoMensagem = tipo;
        labelMensagem.setText(mensagem);
        
        String caminho = System.getProperty("user.dir") + "\\src\\main\\java\\com\\mycompany\\autostockcar\\view\\imagens\\";
        
        if (tipo.equals(TipoMensagem.SUCESSO)) {
            labelMensagem.setIcon(new ImageIcon(caminho + "sucesso.png"));
        } else {
            labelMensagem.setIcon(new ImageIcon(caminho + "erro.png"));
        }
        
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D graphics2d = (Graphics2D) g;
        
        if (this.tipoMensagem == TipoMensagem.SUCESSO) {
            graphics2d.setColor(new Color(15, 174, 34));
        } else {
            graphics2d.setColor(new Color(240, 52, 53));
        }
        
        graphics2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.9f));
        
        graphics2d.fillRect(0, 0, getWidth(), getHeight());
        graphics2d.setComposite(AlphaComposite.SrcOver);
        graphics2d.setColor(new Color(245, 245, 245));
        graphics2d.drawRect(0, 0, getWidth() -1, getHeight());

        
        super.paintComponents(g);
    }

    public boolean isMostra() {
        return mostra;
    }

    public void setMostra(boolean mostra) {
        this.mostra = mostra;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMensagem = new javax.swing.JLabel();

        labelMensagem.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        labelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setText("Mensagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMensagem;
    // End of variables declaration//GEN-END:variables
}
